# Generated by Django 3.1.7 on 2021-03-24 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BedAvailability',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(default='FREE', max_length=20)),
                ('patient_name', models.CharField(blank=True, max_length=100, null=True)),
                ('generated', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
