# Generated by Django 3.1.7 on 2021-03-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_auto_20210324_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='bedavailability',
            name='type',
            field=models.CharField(default='General', max_length=30),
            preserve_default=False,
        ),
    ]
