# Generated by Django 3.1.7 on 2021-03-24 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bed_management_system', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Portfolios',
            new_name='BedAvailability',
        ),
    ]
