# Generated by Django 3.1.7 on 2021-03-24 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bed_management_system', '0002_auto_20210324_0820'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BedAvailability',
        ),
    ]
